apiVersion: v1
kind: Service
metadata:
  namespace: area51
  name: cicd-demo-app-svc
spec:
  selector:
    app: cicd-demo-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080